# TsAnalyzer Server Configuration
# Format: <Stream-ID> <URL> [Options]

# 全局配置
GLOBAL http_port 8081
GLOBAL srt_port 9000

# 1. 传统的 UDP 接收
STR-1  udp://0.0.0.0:19001
STR-2  udp://0.0.0.0:19002
STR-3  udp://0.0.0.0:19003
STR-4  udp://0.0.0.0:19004
